#参考 https://blog.csdn.net/lizheng1992123/article/details/81608007
server:
  port: 8080
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource  #  配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver  #  配置mysql的驱动程序类
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8         #  数据库连接地址
    username: root  #  数据库用户名
    password: root  #  数据库密码
    filters: stat,wall,log4j                      #  配置druid过滤器，开启监控
    dbcp2:                                        #  进行数据库连接池的配置
      min-idle: 5                                 #  数据库连接池的最小维持连接数
      initial-size: 5                             #  初始化提供的连接数
      max-total: 5                                #  最大连接数
      max-wait-millis: 200                        #  等待连接获取的最大超时时间
spring.thymeleaf:   #thymeleaf配置,这里是可以省略的，因为默认配置已经足够
  cache: false  #关闭缓存，及时刷新页面,这一点很重要
#  prefix: classpath:/templates/   #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
#  suffix: .html   #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
#  mode: HTML5   #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
#  encoding: UTF-8   #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
#  servlet.content-type: text/html   #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
spring.devtools.restart:  #设置热部署
  enabled: true   #开启热部署
  additional-paths: src/main/java   #重启范围
#spring.redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 12345
#    timeout: 2000
#    jedis.pool:
#      #jedis最大分配对象
#      maxTotal: 1024
#      #jedis最大保存idel状态对象数
#      maxIdle: 200
#      #jedis池没有对象返回时，最大等待时间
#      maxWaitMillis: 1000
#      testOnBorrow: true
#      testOnReturn: true
#      blockWhenExhausted: false
#    pool:
#      max-active: 8
#      max-wait: 1
#      max-idle: 8
#      min-idle: 0
mybatis: 
  configLocation: 
    classpath: mybatis/mybatis-config.xml  #  mybatis主配置文件所在路径
    map-underscore-to-camel-case: true  #开启驼峰映射
  typeAliasesPackage: springboot.mybatis.commonMapper.model  #  定义所有操作类的别名所在包
  mapper-locations: classpath:mybatis/*/mapper/*.xml  #  所有的mapper映射文件（mapper接口映射过来的xml局部配置文件）
mapper: 
  mappers: tk.mybatis.mapper.common.Mapper  #通用mapper的所在接口名称 不只是包名
  identity: MYSQL #数据库
pagehelper:                       #pagehelper分页插件
    helperDialect: mysql          #设置数据库方言
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql  
#logging:
#  config: classpath:logback-admin.xml
#log:
#  level:
#    root: info
#    my: debug
#  file: logs/admin-server.log
#  maxsize: 30MB
    
    